# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: policies
commonLabels:
  app: policies

generatorOptions:
  disableNameSuffixHash: true

# list of Resource Config to be Applied
resources:
  - channel.yaml
  - subscription.yaml
  - placement.yaml
##  - application.yaml
 

patchesJson6902:
# - path: application_patch.json
#   target:
#     group: app.k8s.io
#     version: v1beta1
#     kind: Application
#     name: demo-stable-policies-app
# - path: placement_template.json
#   target:
#     group: apps.open-cluster-management.io
#     version: v1
#     kind: PlacementRule
#     name: demo-stable-policies-placement
- path: subscription_placement_template.json
  target:
    group: apps.open-cluster-management.io
    version: v1
    kind: Subscription
    name: demo-stable-policies-sub
# - path: subscription_template.json
#   target:
#     group: apps.open-cluster-management.io
#     version: v1
#     kind: Subscription
#     name: demo-stable-policies-sub
# - path: channel_template.json
#   target:
#     group: apps.open-cluster-management.io
#     version: v1
#     kind: Channel
#     name: demo-stable-policies-chan
